#!/bin/bash
clear

directory=$1
moduleName=$0

echo "🐍 NKSmartVIPER"
echo "© Created by Nick Kopilovskii https://github.com/nkopilovskii/SmartVIPER"
echo

readonly DATE=`date +%d.%m.%Y`

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/Module"
SUPPORT_FILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/Module/SupportFiles"

function generateTemplates () {
  echo "Please enter module name ~>"
  read moduleName

  cd $(cd $directory; pwd) && mkdir $moduleName && cd $moduleName
  cp -R $SCRIPT_DIR/*.swift $PWD

  for i in *.swift ; do
    mv $i `echo "$i"|awk -F'.' '{print "'$moduleName'"$1"."$2}'`
    sed -i '' 's/$MODULE_NAME/'$moduleName'/g' *.swift
    sed -i '' 's/$CREATE_DATE/'$DATE'/g' *.swift
    sed -i '' 's/$USER/'$USER'/g' *.swift
  done

  mkdir "SupportFiles" && cd "SupportFiles"
  cp -R $SUPPORT_FILES_DIR/*.* $PWD

  for i in *.* ; do
    mv $i `echo "$i"|awk -F'.' '{print "'$moduleName'."$2}'`
    sed -i '' 's/$MODULE_NAME/'$moduleName'/g' *.*
    sed -i '' 's/$CREATE_DATE/'$DATE'/g' *.*
    sed -i '' 's/$USER/'$USER'/g' *.*
  done
  
  echo "~Templates created~"
  askContinue
}

function enterDirectory () {
  echo "Please enter directory path ~> "
  read directory

  if [[ -d $directory ]]; then
  echo
  generateTemplates
  else
    echo "~Invalid directory!~"
    enterDirectory
  fi
}

function askContinue () {
  read -r -p "Do you want continue? [Yes/No] " response
  case "$response" in
    [yY][eE][sS]|[yY])
        cd ..
        generateTemplates
        ;;
    *)
    echo "🐍Thank You & Good Luck!"  ;;
esac
}


enterDirectory

exit 0
